### ISSUE TITLE
pointnet_sa_module_spec(structure='spec')

### ISSUE THREAD

**Issue by xiashaobo** [fate3439/LocalSpecGCN#4]
Thank you for your awesome work and good codes. 
I have a question about the parameter in "pointnet_sa_module_spec".

According to the codes, pointnet_sa_module_spec is used to do the graph convolution.  As the "structure='spec'" is used,  "spec_conv2d()" in pointnet_util.py file is used, not the "spec_conv2d_modul()"
And, based on the codes in spec_graph_util.py file,  the difference lies in: " filtered = tf.matmul( W_modulation , inputs_fourier)" which is contained in "spec_conv2d_modul()".

If my understanding is right, the  "spec_conv2d_modul()" should be used based on Eq.(10)  in the paper. 

So, my question is why use "spec_conv2d()" instead of  "spec_conv2d_modul()" ?

**Comment by fate3439** [comment]
Hi,

The spec_modul model adds frequency modulation, as per spectral graph convolution definition. Based on my experiments, the effect of modulation does not give much improvement than simply modulate it with an identity matrix, which is the default spec model as used in the spec_conv2d(). You are welcome to try whichever version that works best for you. That's why I included both versions...

Thanks for your interest.
Chu.

**Comment by xiashaobo** [comment]
> Hi,
> 
> The spec_modul model adds frequency modulation, as per spectral graph convolution definition. Based on my experiments, the effect of modulation does not give much improvement than simply modulate it with an identity matrix, which is the default spec model as used in the spec_conv2d(). You are welcome to try whichever version that works best for you. That's why I included both versions...
> 
> Thanks for your interest.
> Chu.

Got it. Many thanks~ 
I will try these models in my datasets.
